version: '3'

services:
  app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app

  db:
    build: ./db
    environment:
      MONGODB_ROOT_PASSWORD: root
      MONGODB_ROOT_SET_MODE: primary
      MONGODB_DATABASE: nest
    volumes:
      - mongodb_data:/bitnami/mongodb

volumes:
  mongodb_data:
    driver: local
